### PR TITLE
Fix: Deployed by filter capitalization

### LINKED ISSUE #291: The deployedBy filter in the deployments endpoint is not filtering the deployments properly
See this case:
https://peer.decentraland.org/content/entities/profile?pointer=0xa7c825bb8c2c4d18288af8efe38c8bf75a1aab51

This call returns many deployments (207 at the time when this issue was created):
https://peer.decentraland.org/content/deployments?entityType=profile&pointer=0xa7c825bb8c2c4d18288af8efe38c8bf75a1aab51

However this other call is returning only one deployment:
https://peer.decentraland.org/content/deployments?entityType=profile&deployedBy=0xa7c825bb8c2c4d18288af8efe38c8bf75a1aab51

@nchamo suggested that the problem may be caused by the deployedBy filter, which may take into account the word casing of the filter address.

### PR DESCRIPTION
**Pull request by jmoguilevsky**
This PR:
- Introduces a new index for deployer_address for the lowercase of the column, since we'll be searching ignoring case, but saving values as they come
- Creates a test suite for DeploymentRepository, achieving ~100% coverage mocking the database
- Fixes a bug in the `createOrClause` method where the timestamp type was hardcoded and didn't change based on the filter type
- Modifies the query for deployer_address so that it looks for the LOWER of the incoming address
- Modifies some queries from multiline to single line to make them more testable

Fixes #291

### CODE REVIEW

File: content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { MigrationBuilder } from 'node-pg-migrate'
+
+/*
+  In this migration, we are creating a index in deployments table with the 'entity_timestamp' and 'entity_id' columns
+ */
+
+export async function up(pgm: MigrationBuilder): Promise<void> {
+  pgm.sql(`CREATE INDEX deployer_address_lower_case on deployments (LOWER(deployer_address) text_pattern_ops);`)
```
Comment (agusaldasoro) [inline content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts:8]: Should we delete the original index on `deployer_address` ?

File: content/src/repository/extensions/DeploymentsRepository.ts [hunk 2]
```diff
@@ -175,23 +176,18 @@ export class DeploymentsRepository {
 
   private createOrClause(timestampField: string, compare: string, timestampFilter: string): string {
     const equalWithEntityIdComparison = `(LOWER(dep1.entity_id) ${compare} LOWER($(lastId)) AND dep1.${timestampField} = to_timestamp($(${timestampFilter}) / 1000.0))`
-    const timestampComparison = `(dep1.entity_timestamp ${compare} to_timestamp($(${timestampFilter}) / 1000.0))`
+    const timestampComparison = `(dep1.${timestampField} ${compare} to_timestamp($(${timestampFilter}) / 1000.0))`
```
Comment (agusaldasoro) [inline content/src/repository/extensions/DeploymentsRepository.ts:179]: 👏

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 3]
```diff
@@ -0,0 +1,456 @@
...
+
+      beforeEach(() => {
+        when(db.map(anything(), anything(), anything())).thenReturn(Promise.resolve(dbResult))
+      })
+
+      it('should return a map of entity id to the deployment status', async () => {
+        const entities = ['1', '3']
+        const result = await repository.areEntitiesDeployed(entities)
+
+        expect(result).toEqual(
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:33]: I'd remove this as the only thing that you are testing is the mock

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 4]
```diff
@@ -0,0 +1,456 @@
...
+      result = await repository.getAmountOfDeployments()
+    })
+
+    it('should call the database with the expected query', () => {
+      verify(
+        db.map(`SELECT entity_type, COUNT(*) AS count FROM deployments GROUP BY entity_type`, deepEqual([]), anything())
+      ).once()
+    })
+
+    it('should return a Map with the result', () => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:78]: Same as before

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 5]
```diff
@@ -0,0 +1,456 @@
...
+
+    beforeEach(async () => {
+      db = mock(MockedDataBase)
+      repository = new DeploymentsRepository(instance(db) as any)
+
+      when(db.map(anything(), anything(), anything())).thenReturn(Promise.resolve(expectedResult))
+      result = await repository.getAmountOfDeployments()
+    })
+
+    it('should call the database with the expected query', () => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:72]: Let's give more detail here, something like `the db makes a count`

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 6]
```diff
@@ -0,0 +1,456 @@
...
+      ).once()
+    })
+
+    it('should return a Map with the result', () => {
+      expect(result).toEqual(new Map(expectedResult as any))
+    })
+  })
+
+  describe('getHistoricalDeployments', () => {
+    beforeEach(() => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:84]: Is this `beforeEach` necessary?

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 7]
```diff
@@ -0,0 +1,456 @@
...
+    })
+
+    describe("when it doesn't receive a lastId", () => {
+      beforeEach(() => {
+        db = mock(MockedDataBase)
+        repository = new DeploymentsRepository(instance(db) as any)
+      })
+
+      describe('when it receives a field or order to sort by', () => {
+        beforeEach(() => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:96]: I'm not sure why you need the nested beforeEach, should this be all one only describe?

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 8]
```diff
@@ -0,0 +1,456 @@
...
+            {
+              field: SortingField.ENTITY_TIMESTAMP,
+              order: SortingOrder.ASCENDING
+            }
+          )
+
+          const args = capture(db.map).last()
+
+          expect(args[0]).toContain(`ORDER BY dep1.entity_timestamp ASC`)
+          expect(args[0]).toContain(
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:114]: niceeeeee 👏

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 9]
```diff
@@ -0,0 +1,456 @@
...
+
+        expect(result).toEqual(
+          new Map([
+            ['1', true],
+            ['3', false]
+          ])
+        )
+
+        verify(
+          db.map('SELECT entity_id FROM deployments WHERE entity_id IN ($1:list)', deepEqual([entities]), anything())
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:41]: can we test the content of the params in the query too?

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 10]
```diff
@@ -0,0 +1,456 @@
...
+          )
+          expect(args[1]).toEqual(jasmine.objectContaining({ fromLocalTimestamp: 1, toLocalTimestamp: 11 }))
+        })
+      })
+    })
+
+    describe('when it receives a lastId', () => {
+      const lastId = '1'
+
+      beforeEach(() => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:143]: As we don't really care about the response from the MockedDataBase can we configure this only once for the entire file?

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 11]
```diff
@@ -0,0 +1,456 @@
...
+    describe('when there is a deployed by filter', () => {
+      beforeEach(() => {
+        db = mock(MockedDataBase)
+        repository = new DeploymentsRepository(instance(db) as any)
+
+        when(db.map(anything(), anything(), anything())).thenReturn(Promise.resolve([]))
+      })
+
+      it('should add the expected where clause to the query with the addresses on lowercase', async () => {
+        const deployedBy = ['jOn', 'aGus']
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:211]: 🤣

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 12]
```diff
@@ -0,0 +1,456 @@
...
+        await repository.getHistoricalDeployments(0, 10, { deployedBy })
+
+        const args = capture(db.map).last()
+
+        expect(args[0]).toContain(`LOWER(dep1.deployer_address) IN ($(deployedBy:list))`)
+        expect(args[1]).toEqual(jasmine.objectContaining({ deployedBy: deployedBy.map((x) => x.toLowerCase()) }))
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:217]: nit: as this is the expected param, shouldn't it be hardcoded?

**Review by agusaldasoro — CHANGES_REQUESTED** [review]
Great Work! Just a few comments, also do you mind adding an integration test that executes the same behaviour as described in the bug report?

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 3 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:33]: This is asserting on the logic of the map creation in the return statement of the function

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 13]
```diff
@@ -0,0 +1,456 @@
...
+          ])
+        )
+
+        verify(
+          db.map('SELECT entity_id FROM deployments WHERE entity_id IN ($1:list)', deepEqual([entities]), anything())
+        ).once()
+      })
+    })
+
+    describe('when the entities list is empty', () => {
```
[the remark this answers is not in the document]
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:48]: This is asserting on the first if of the function (https://github.com/decentraland/catalyst/blob/774344fb9ff5fd3d27adf29fb09bab7d136050a4/content/src/repository/extensions/DeploymentsRepository.ts#L20) that's why It also asserts on `never called` of the mock

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 5 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts]: Done

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 4 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:80]: As before, this asserts that the response is a map with the result of the DB call as the content

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 7 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts]: Yes, deleted the nested beforeEaches

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 6 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts]: This one is, not the inner ones

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 12 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts]: Updated to have it hardcoded

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 10 above)
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:133]: We can, but that makes the tests coupled since the mock is the same among all tests

Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:133]: That's why I initialized it in each test context

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 14]
```diff
@@ -0,0 +1,456 @@
...
+    })
+
+    describe('when the entities list is not empty', () => {
+      const dbResult = ['1', '2']
+
+      beforeEach(() => {
+        when(db.map(anything(), anything(), anything())).thenReturn(Promise.resolve(dbResult))
+      })
+
+      it('should return a map of entity id to the deployment status', async () => {
```
[the remark this answers is not in the document]
Comment (jmoguilevsky) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:32]: This is the correct verification, splitted the test for two different verifications

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 3 above)
Comment (agusaldasoro) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:33]: My bad!

File: content/test/unit/repository/DeploymentsRepository.spec.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (agusaldasoro) [reply content/test/unit/repository/DeploymentsRepository.spec.ts:48]: My bad!

File: content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts [hunk 15]
```diff
@@ -0,0 +1,14 @@
...
+  In this migration, we are creating a index in deployments table with the 'entity_timestamp' and 'entity_id' columns
+ */
+
+export async function up(pgm: MigrationBuilder): Promise<void> {
+  pgm.sql(`DROP INDEX deployments_deployer_address_index;`)
+  pgm.sql(`CREATE INDEX deployer_address_lower_case on deployments (LOWER(deployer_address) text_pattern_ops);`)
+}
+
+export async function down(pgm: MigrationBuilder): Promise<void> {
+  pgm.sql(`DROP INDEX deployer_address_lower_case;`)
```
Comment (agusaldasoro) [inline content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts:13]: If we are maintaining those down functions then we should create the original index here

File: content/test/unit/repository/DeploymentsRepository.spec.ts [hunk 16]
```diff
@@ -0,0 +1,402 @@
...
+  let repository: DeploymentsRepository
+  let db: MockedDataBase
+
+  beforeEach(() => {
+    db = mock(MockedDataBase)
+    repository = new DeploymentsRepository(instance(db) as any)
+  })
+
+  describe('areEntitiesDeployed', () => {
+    beforeEach(() => {
```
Comment (agusaldasoro) [inline content/test/unit/repository/DeploymentsRepository.spec.ts:17]: Is this necessary as you have the beforeEach above with the same code?

**Review by agusaldasoro — APPROVED** [review]
Great work, especially creating the repository tests! 👏

Just check the two comments and then you are free to merge.
