### PR TITLE
fix: memory leak while syncing from scratch

### LINKED ISSUE #1427: Content Server:  Memory Leaks while syncing from scratch
While developing the on-chain validations, some memory leaks were detected on the content server.

### PR DESCRIPTION
**Pull request by hugoArregui**
Fixes #1427

### CODE REVIEW

File: content/src/service/synchronization/batchDeployer.ts [hunk 1]
```diff
@@ -109,81 +109,88 @@ export function createBatchDeployerComponent(
...
-                components,
-                entity.entityId,
-                entity.entityType,
-                entity.authChain,
-                elementInMap.servers,
-                DeploymentContext.SYNCED
-              )
-              wasEntityProcessed = true
+      try {
+        await parallelDeploymentJobs.onSizeLessThan(1000)
```
Comment (menduz) [inline content/src/service/synchronization/batchDeployer.ts:116]: I think this condition will render `operationPriority` useless, should this condition be "priority aware"?
```suggestion
        await parallelDeploymentJobs.onSizeLessThan(1000, operationPriority)
```

Comment (hugoArregui) [reply content/src/service/synchronization/batchDeployer.ts:116]: I don't think so, this is just to put a bound on it, the 1000 elements have their priority.

**Review by marianogoldman — APPROVED** [review]
